<a href="https://colab.research.google.com/github/kgreen1111/numpy-mini-project-makeSenseOfCensus/blob/main/NumPy_Mini_Project_makeSenseOfCensus.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

data_file ='/content/makeSenseOfCensus.csv'

In [2]:
data = np.genfromtxt(data_file, dtype='int64', delimiter=",", skip_header=1)

print("\nData: \n\n", data)


Data: 

 [[39 13  4 ...  0 40  0]
 [50 13  4 ...  0 13  0]
 [38  9  4 ...  0 40  0]
 ...
 [48 13  4 ...  0 58  1]
 [40 10  4 ...  0 40  0]
 [39 13  4 ...  0 50  1]]


In [3]:
print("\nType of data: \n\n", type(data))


Type of data: 

 <class 'numpy.ndarray'>


In [4]:
new_record = [[50, 9, 4, 1, 0, 0, 40, 0]]

data = np.concatenate((data,new_record),axis=0)

In [5]:
age = data[:,0]

max_age = np.max(age)
print(f"max age: {max_age}")
min_age = np.min(age)
print(f"min age: {min_age}")
age_mean = np.mean(age)
print(f"mean age: {age_mean}")
age_std = np.std(age)
print(f"standard deviation of age: {age_std}")

max age: 90
min age: 17
mean age: 38.06293706293706
standard deviation of age: 13.341478176165857


In [6]:
race = data[:,2]

race_0 = (race[race==0])
race_1 = (race[race==1])
race_2 = (race[race==2])
race_3 = (race[race==3])
race_4 = (race[race==4])

len_0 = len(race_0)
len_1 = len(race_1)
len_2 = len(race_2)
len_3 = len(race_3)
len_4 = len(race_4)

print("Totals by Race:")
print("---------------")
print(f"Amer-Indian-Eskimo: {len_0}")
print(f"Asian-Pac-Islander: {len_1}")
print(f"Black: {len_2}")
print(f"Other: {len_3}")
print(f"White: {len_4}")

Totals by Race:
---------------
Amer-Indian-Eskimo: 10
Asian-Pac-Islander: 27
Black: 110
Other: 6
White: 848


In [7]:
race_array = np.array([len_0,len_1,len_2,len_3,len_4])
minority_race = np.min(race_array)

if len_0 ==minority_race:
  print(f"The race with the fewest citizens is 'Amer-Indian-Eskimo' with {len_0} total citizens.")
elif len_1 ==minority_race:
  print(f"The race with the fewest citizens is 'Asian-Pac-Islander' with {len_1} total citizens.")
elif len_2 ==minority_race:
  print(f"The race with the fewest citizens is 'Black' with {len_2} total citizens.")
elif len_3 ==minority_race:
  print(f"The race with the fewest citizens is 'Other' with {len_3} total citizens.")
else:
  print(f"The race with the fewest citizens is 'White' with {len_4} total citizens.")

The race with the fewest citizens is 'Other' with 6 total citizens.


In [8]:
age = data[:,0]
senior_citizens = (data[age>=61])

working_hours_sum = np.sum(senior_citizens[:,6])
senior_citizens_len = len(senior_citizens)

print(f"There are {senior_citizens_len} senior citizens.")
print(f"Together, the senior citizen population works a total of {working_hours_sum} per week.")

There are 61 senior citizens.
Together, the senior citizen population works a total of 1917 per week.


In [9]:
avg_working_hours = working_hours_sum/senior_citizens_len

print(f"The average working hours for senior citizens is {avg_working_hours}.")
if avg_working_hours >25:
  print("The average is higher than the recommended maximum of 25 hours per week.")
elif avg_working_hours ==25:
  print("The average is equal to the recommended maximum of 25 hours per week.")
else:
  print("The average is below the recommended maximum of 25 hours per week.")

The average working hours for senior citizens is 31.42622950819672.
The average is higher than the recommended maximum of 25 hours per week.


In [10]:
education = data[:,1]
high = (data[education>10])
low = (data[education<= 10])

avg_pay_high = np.mean(high[:,7])
avg_pay_low = np.mean(low[:,7])

print(f"Mean income of citizens with more than 10 years of education: {avg_pay_high}.")
print(f"Mean income of citizens with 10 or fewer years of education: {avg_pay_low}.")
print("")

if avg_pay_high > avg_pay_low:
  print("The data shows higher educated people are paid higher on average.")
elif avg_pay_high == avg_pay_low:
  print("The data shows equal pay distribution regardless of the educational background citizens had.")
else:
  print("The data shows higher educated people are not paid higher on average.")

Mean income of citizens with more than 10 years of education: 0.42813455657492355.
Mean income of citizens with 10 or fewer years of education: 0.13649851632047477.

The data shows higher educated people are paid higher on average.
